name: CI

on:
    push:
    pull_request:

jobs:
    build:

        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-verison: [12.x, 14.x]

        steps:
        -   uses: actions/checkout@v2
        -   name: Cache node modules
            uses: actions/cache@v1
            with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-node-
        -   name: npm install and build
            run: |
                npm ci
                npm run build
            working-directory: ./frontend
        -   name: setup JDK 1.11
            uses: actions/setup-java@v1
            with: 
                java-version: 1.11
                

        -   name: Build with maven
            run: |
                echo "${{ secrets.CLIENT_KEYSTORE }}" > client.keystore.p12.asc
                gpg -d --passphrase "{{ secrets.CLIENT_KEYSTORE_KEY }}" --batch client.keystore.p12.asc > client.keystore.p12
                echo "Successfully created keystore."
                echo "${{ secrets.CLIENT_TRUSTSTORE }}" > client.truststore.jks.asc
                gpg -d --passphrase "{{ secrets.CLIENT_TRUSTSTORE_KEY }}" --batch client.truststore.jks.asc > client.truststore.jks
                echo "Successfully created truststore."
                mvn -B --no-transfer-progress package --file pom.xml
            working-directory: ./backend

    test:
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [12.x, 14.x]
        
        steps:
        -   uses: actions/checkout@v2
        -   name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
        -   name: npm install, and test
            run: |
                npm install
                npm test
            working-directory: ./frontend
            env:
                CI: true
